ledquence Alpha: bushardware.h File Reference
bushardware.h File Reference
#include <FastLED.h>
#include <pixeltypes.h>
#include <sam3xa/include/instance/instance_pioa.h>
#include <UARTClass.h>
#include <variant.h>
#include <Wire.h>
#include "Adafruit_MPR121.h"
#include <Adafruit_NeoPixel.h>
Macros
#define DATA_PIN 6
#define NUM_LEDS 40
Functions
void showLeds ()
void readButtons ()
void setDebounce ()
void portsetup ()
Variables
CRGB leds [NUM_LEDS]
Adafruit_MPR121 touchboard [4] = { Adafruit_MPR121() }
Adafruit_NeoPixel strip = Adafruit_NeoPixel(40, DATA_PIN, NEO_GRB + NEO_KHZ800)
Macro Definition Documentation
#define DATA_PIN 6
Definition at line 15 of file bushardware.h.
#define NUM_LEDS 40
Definition at line 16 of file bushardware.h.
Function Documentation
void portsetup ()
Definition at line 53 of file bushardware.h.
References setDebounce(), and strip.
Referenced by setup().
void readButtons ()
Definition at line 32 of file bushardware.h.
Referenced by timer1_handler().
void setDebounce ()
Definition at line 38 of file bushardware.h.
Referenced by portsetup().
void showLeds ()
Definition at line 27 of file bushardware.h.
References strip.
Variable Documentation
CRGB leds[NUM_LEDS]
Definition at line 19 of file bushardware.h.
Adafruit_NeoPixel strip = Adafruit_NeoPixel(40, DATA_PIN, NEO_GRB + NEO_KHZ800)
Definition at line 25 of file bushardware.h.
Referenced by colorWipe(), portsetup(), rainbow(), rainbowCycle(), showLeds(), theaterChase(), theaterChaseRainbow(), and Wheel().
Adafruit_MPR121 touchboard[4] = { Adafruit_MPR121() }
Definition at line 22 of file bushardware.h.