ledquence Alpha: Menu Class Reference
Menu Class Reference
menu class for menu handling.
#include <menu.h>
Public Member Functions
Menu ()
void onUpdate (void(*)(int, int))
on Update callback brief
void do_your_things (int, int)
this is the mainloop of menu
int get_page ()
returns actual page as int
int get_bar ()
returns actual bar position as int
int get_indicatorleds ()
get indicatorleds
int get_stepleds ()
get stepleds
Detailed Description
menu class for menu handling.
Menu It defines menu related functions and callbacks!
Definition at line 34 of file menu.h.
Constructor & Destructor Documentation
Menu::Menu ()
Definition at line 10 of file menu.cpp.
References MenuEnums::Main.
Member Function Documentation
void Menu::do_your_things (int fb, int sb)
this is the mainloop of menu
Menu Mainloop processes all the button and led data according to selected page needs to get updated regularly in mainloop
Parameters
fb functionbuttons
sb stepbuttons
Definition at line 120 of file menu.cpp.
References DEBUG, and MenuEnums::Main.
Referenced by loop().
int Menu::get_bar ()
returns actual bar position as int
int Menu::get_indicatorleds ()
get indicatorleds
get the data for the indicator leds . process the datahandling to update the stepleds. get the according data for page. returns an int 16 states. todo: return 16 colors!.
Definition at line 51 of file menu.cpp.
References MenuEnums::Main, MenuEnums::Pattern, and MenuEnums::Sequence.
Referenced by loop().
int Menu::get_page ()
returns actual page as int
Definition at line 41 of file menu.cpp.
Referenced by alive1(), and loop().
int Menu::get_stepleds ()
get stepleds
process the datahandling to update the stepleds. get the according data for page. returns an int 16 states. todo: return 16 colors!.
Definition at line 71 of file menu.cpp.
References MenuEnums::Main, and MenuEnums::Sequence.
Referenced by loop().
void Menu::onUpdate (void(*)(int, int) function)
on Update callback brief
onUpdate callback detail
Parameters
function callback function pointer. gets called by ??. and processes the events
Definition at line 22 of file menu.cpp.
Referenced by setup().
The documentation for this class was generated from the following files:
menu.h
menu.cpp