ledquence Alpha: porthardware.h File Reference
porthardware.h File Reference
#include <Arduino.h>
Functions
bool get_bit (int val, int pos)
void readinSB ()
void readinFB ()
void readButtons ()
void update_mux (int index)
void muxoutirq (int i)
void update_trg ()
void setDebounce ()
void portsetup ()
Variables
bool mux1 [16]
bool mux2 [16]
bool mux3 [16]
Function Documentation
bool get_bit (int val, int pos)
Definition at line 11 of file porthardware.h.
Referenced by update_mux(), and update_trg().
void muxoutirq (int i)
Definition at line 140 of file porthardware.h.
References mux1, mux1A0, mux1A1, mux1A2, mux1A3, mux2, mux2A0, mux2A1, mux2A2, mux2A3, mux3, mux3A0, mux3A1, mux3A2, mux3A3, and muxlatch.
Referenced by timer2_handler().
void portsetup ()
Definition at line 202 of file porthardware.h.
References clkout, FB01, FB02, FB03, FB04, FB05, FB06, FB07, FB08, mux1A0, mux1A1, mux1A2, mux1A3, mux2A0, mux2A1, mux2A2, mux2A3, mux3A0, mux3A1, mux3A2, mux3A3, muxlatch, SB01, SB02, SB03, SB04, SB05, SB06, SB07, SB08, SB09, SB10, SB11, SB12, SB13, SB14, SB15, SB16, Tout01, Tout02, Tout03, Tout04, Tout05, Tout06, Tout07, Tout08, Tout09, Tout10, Tout11, Tout12, Tout13, Tout14, Tout15, and Tout16.
void readButtons ()
Definition at line 49 of file porthardware.h.
References readinFB(), and readinSB().
void readinFB ()
Definition at line 36 of file porthardware.h.
References FB01, FB02, FB03, FB04, FB05, FB06, FB07, and FB08.
Referenced by readButtons().
void readinSB ()
Definition at line 15 of file porthardware.h.
References SB01, SB02, SB03, SB04, SB05, SB06, SB07, SB08, SB09, SB10, SB11, SB12, SB13, SB14, SB15, and SB16.
Referenced by readButtons().
void setDebounce ()
Definition at line 182 of file porthardware.h.
References FB01, FB02, FB03, FB04, FB05, FB06, FB07, and FB08.
void update_mux (int index)
Definition at line 54 of file porthardware.h.
References get_bit(), mux1, mux2, and mux3.
Referenced by timer2_handler().
void update_trg ()
Definition at line 162 of file porthardware.h.
References get_bit(), Tout01, Tout02, Tout03, Tout04, Tout05, Tout06, Tout07, Tout08, Tout09, Tout10, Tout11, Tout12, Tout13, Tout14, Tout15, and Tout16.
Referenced by timer2_handler().
Variable Documentation
bool mux1[16]
Definition at line 7 of file porthardware.h.
Referenced by muxoutirq(), and update_mux().
bool mux2[16]
Definition at line 8 of file porthardware.h.
Referenced by muxoutirq(), and update_mux().
bool mux3[16]
Definition at line 9 of file porthardware.h.
Referenced by muxoutirq(), and update_mux().